// SinGL v0.04.01
// file assembled from mesh/src/Solid.sg
// ---   *   ---   *   ---
// LIBRE BOILERPASTE
// GENERATED BY AR/AVTOMAT
//
// LICENSED UNDER GNU GPL3
// BE A BRO AND INHERIT
//
// COPYLEFT IBN-3DILA 2022
// ---   *   ---   *   ---

#ifndef __SOLID_H__
#define __SOLID_H__



// ---   *   ---   *   ---
// deps

  #include <glm/vec4.hpp>
  #include "sin/shader/Params.hpp"
  #include "sin/mesh/Vertex.hpp"


// ---   *   ---   *   ---
// ROM



// ---   *   ---   *   ---


namespace shader::mesh {
  const char* Solid_vert=R"glsl(
;
void main(void) {
  vec4 co=extract_xyz();

  gl_Position=apply_transform(co);
  Tex_Coords=extract_tex();
};



  )glsl";


// ---   *   ---   *   ---


  const char* _DULL_SYNTAX_v_Solid_vert[]={
      shader::version_vert,
      shader::mesh::Vertex_vert,
      Solid_vert
  };

  const char* Solid_frag=R"glsl(
in vec2 Tex_Coords;
flat in uint Tile_Index;;
uniform sampler2DArray Surface;
out vec4 Frag_Color;
void main(void) {
  ivec3 dim=textureSize(Surface,0);
  float uv_step=(1.0f / dim[0])*16;

  Frag_Color=
    texture(Surface,vec3(Tex_Coords*uv_step,0));
}



  )glsl";


// ---   *   ---   *   ---


  const char* _DULL_SYNTAX_f_Solid_frag[]={
      shader::version_frag,
      Solid_frag
  };

  const Params Solid={
    .source_v=_DULL_SYNTAX_v_Solid_vert,
    .source_v_sz=3,
    .source_f=_DULL_SYNTAX_f_Solid_frag,
    .source_f_sz=2,
    .attrs={
      "Vertex"
    },
    .num_attrs=1,
    .uniforms={
      "Model",
      "View"
    },
    .num_uniforms=2,
    .ubos={

    },
    .num_ubos=0,
    .ssbos={
      "Tile_Indices"
    },
    .num_ssbos=1,
    .samplers={
      "Surface"
    },
    .num_samplers=1,
  };
};


// ---   *   ---   *   ---



// ---   *   ---   *   ---


#endif // __SOLID_H__


